ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS delivery_pin VARCHAR(4),
ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS ready_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS received_at TIMESTAMPTZ;
