import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabaseAdmin';
import { authorizeRequest, unauthorizedResponse } from '@/lib/apiAuth';
import { logAdminAction } from '@/lib/adminAudit';

export const dynamic = 'force-dynamic';

type PinType = 'delivery' | 'pickup' | 'both';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Admin regenerates the order PIN(s).
 * - PINs are generated by generate_delivery_pin / generate_pickup_pin (service_role only).
 * - The new PIN is NEVER returned: buyer/store see it in their own panel.
 * - Resets the attempt counters and moves PIN_LOCKED → DELIVERING.
 */
export async function POST(request: Request) {
  const auth = await authorizeRequest(request, ['admin']);
  if (!auth.authorized) {
    return unauthorizedResponse(auth.error);
  }

  const adminId: string | null = auth.user?.id || auth.profile?.id || null;

  try {
    const body: unknown = await request.json().catch(() => null);
    const input = body && typeof body === 'object' ? (body as Record<string, unknown>) : {};
    const orderId = input.orderId;
    const pinType: PinType = input.pinType === 'pickup' || input.pinType === 'delivery' ? input.pinType : 'both';

    if (typeof orderId !== 'string' || !UUID_RE.test(orderId)) {
      return NextResponse.json({ error: 'orderId é obrigatório.' }, { status: 400 });
    }

    const supabase = getSupabaseAdmin();

    const { data: order, error: ordErr } = await supabase
      .from('orders')
      .select('id, status, pin_attempts, pickup_pin_attempts')
      .eq('id', orderId)
      .maybeSingle();

    if (ordErr) {
      console.error('[Regenerate PIN] Erro ao buscar pedido:', ordErr.code);
      return NextResponse.json({ error: 'Falha ao consultar o pedido.' }, { status: 500 });
    }
    if (!order) {
      return NextResponse.json({ error: 'Pedido não encontrado.' }, { status: 404 });
    }

    // 1. Gerar os PINs pelas funções do banco (o valor retornado é descartado)
    if (pinType !== 'pickup') {
      const { error } = await supabase.rpc('generate_delivery_pin', { p_order_id: order.id });
      if (error) {
        console.error('[Regenerate PIN] generate_delivery_pin falhou:', error.code);
        return NextResponse.json({ error: 'Falha ao gerar o novo PIN de entrega.' }, { status: 500 });
      }
    }
    if (pinType !== 'delivery') {
      const { error } = await supabase.rpc('generate_pickup_pin', { p_order_id: order.id });
      if (error) {
        console.error('[Regenerate PIN] generate_pickup_pin falhou:', error.code);
        return NextResponse.json({ error: 'Falha ao gerar o novo PIN de retirada.' }, { status: 500 });
      }
    }

    // 2. Zerar tentativas e destravar o pedido
    const wasLocked = String(order.status || '').toUpperCase() === 'PIN_LOCKED' || order.status === 'bloqueado_pin';
    const resetPayload: Record<string, unknown> = {};
    if (pinType !== 'pickup') {
      resetPayload.pin_attempts = 0;
      resetPayload.last_pin_attempt_at = null;
    }
    if (pinType !== 'delivery') {
      resetPayload.pickup_pin_attempts = 0;
      resetPayload.last_pickup_pin_attempt_at = null;
    }
    if (wasLocked) {
      resetPayload.status = 'DELIVERING';
    }

    const { error: updErr } = await supabase
      .from('orders')
      .update(resetPayload)
      .eq('id', order.id);

    if (updErr) {
      console.error('[Regenerate PIN] Erro ao destravar pedido:', updErr.code);
      return NextResponse.json({ error: 'PIN gerado, mas falhou ao destravar o pedido. Tente novamente.' }, { status: 500 });
    }

    // 3. Log (sem o PIN)
    await logAdminAction({
      actorId: adminId,
      action: 'REGENERATE_PIN',
      targetType: 'ORDER',
      targetId: String(order.id),
      beforeState: {
        status: order.status,
        pin_attempts: order.pin_attempts ?? null,
        pickup_pin_attempts: order.pickup_pin_attempts ?? null
      },
      afterState: {
        pinType,
        status: wasLocked ? 'DELIVERING' : order.status,
        pin_attempts: pinType !== 'pickup' ? 0 : order.pin_attempts ?? null,
        pickup_pin_attempts: pinType !== 'delivery' ? 0 : order.pickup_pin_attempts ?? null
      },
      request
    });

    return NextResponse.json({
      success: true,
      orderId: order.id,
      status: wasLocked ? 'DELIVERING' : order.status,
      message: 'Novo PIN gerado. O cliente (entrega) e a loja (retirada) veem o código no próprio painel.'
    });
  } catch (error: unknown) {
    console.error('[Regenerate PIN] Erro inesperado:', error instanceof Error ? error.message : 'unknown');
    return NextResponse.json({ error: 'Erro interno ao gerar o PIN.' }, { status: 500 });
  }
}
